### ISSUE TITLE
Redocly does not like nullable fields

### ISSUE THREAD

**Issue by magnusja** [juhaku/utoipa#1050] opened 2024-09-16 12:27 UTC
```
#[derive(Deserialize, Debug, ToSchema, ExternalApiVersioned)]
#[schema(as = types::customer::v1::CustomerInput)]
pub struct CustomerInput {
    pub name: String,
    #[schema(value_type = Option<uuid::Uuid>)]
    pub default_contact_person: Option<UserId>,
    pub customer_number: Option<String>,
    pub language: Option<types::customer::v1::Language>,
    pub vat_id: Option<types::vat::v1::CompleteVatId>,
    pub commercial_register_number: Option<String>,
    pub billing_address: Option<types::customer::v1::CustomerBillingAddress>,
}
```

yields to

```
[10] http://127.0.0.1:5001/openapi.json:1451:25 at #/components/schemas/types.customer.v1.CustomerInput/properties/billing_address/nullable

The `type` field must be defined when the `nullable` field is used.

1449 |     }
1450 |   ],
1451 |   "nullable": true
1452 | },
1453 | "commercial_register_number": {

Error was generated by the spec rule.
```

But I dont know why?

```
 "types.customer.v1.CustomerInput": {
        "type": "object",
        "required": [
          "name",
          "billing_address"
        ],
        "properties": {
          "billing_address": {
            "allOf": [
              {
                "$ref": "#/components/schemas/types.customer.v1.CustomerBillingAddress"
              }
            ],
            "nullable": true
          },
          "commercial_register_number": {
            "type": "string",
            "nullable": true
          },
          "customer_number": {
            "type": "string",
            "nullable": true
          },
          "default_contact_person": {
            "type": "string",
            "format": "uuid",
            "nullable": true
          },
          "language": {
            "allOf": [
              {
                "$ref": "#/components/schemas/types.customer.v1.Language"
              }
            ],
            "nullable": true
          },
          "name": {
            "type": "string"
          },
          "vat_id": {
            "allOf": [
              {
                "$ref": "#/components/schemas/types.vat.v1.CompleteVatId"
              }
            ],
            "nullable": true
          }
        }
      },
```

**Comment by juhaku** [comment] 2024-09-16 22:49
>```json
>"language": {
>  "allOf": [
>    {
>      "$ref": "#/components/schemas/types.customer.v1.Language"
>    }
>  ],
>  "nullable": true
>},
>```

@magnusja I guess the issue lies in these `allOf` fields. The validation rules seems to be quite strict in redoc where it requires that if there is `nullable` defined then there should also be `type` well. Thus this should be define as follows
```json
"language": {
  "allOf": [
    {
      "$ref": "#/components/schemas/types.customer.v1.Language"
    }
  ],
  "nullable": true,
  "type": "object"
},
```

Nonetheless this should get resolved with 5.0.0 version once it is out since it is moving to OpenAPI 3.1 thus the generated schema will be different and this issue will not raise.

**Comment by JMLX42** [comment] 2024-10-15 08:16
The new generated OpenAPI JSON is now:

```json
"language": {
  "allOf": [
    {
      "type": "null"
    },
    {
      "$ref": "#/components/schemas/types.customer.v1.Language"
    }
  ]
}
```

@juhaku is that the expected behavior? Is that the proper OpenAPI 3.1 to make nullable refs?

Because generating a Rust SDK from this will result in an `Option<T>` instead of an `Option<Option<T>>`.

Example:

```rust
   #[serde(rename_all = "camelCase")]
    pub struct GltfResourceSparseRelationshipsObject {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub asset: Option<crate::gltf::AssetResourceRelationshipToOne>,
        #[serde(
            default,
            skip_serializing_if = "Option::is_none",
            with = "::serde_with::rust::double_option",
        )]
        pub scenes: Option<Option<crate::scene::SceneResourceRelationshipToMany>>,
        #[serde(
            default,
            skip_serializing_if = "Option::is_none",
            with = "::serde_with::rust::double_option",
        )]
        pub scene: Option<Option<crate::scene::SceneResourceRelationshipToOne>>,
    }
```

```json
"GltfResourceSparseRelationshipsObject": {
  "type": "object",
  "properties": {
    "asset": {
      "allOf": [
        {
          "type": "null"
        },
        {
          "$ref": "#/components/schemas/AssetResourceRelationshipToOne"
        }
      ]
    },
    "scenes": {
      "allOf": [
        {
          "type": "null"
        },
        {
          "$ref": "#/components/schemas/SceneResourceRelationshipToMany"
        }
      ]
    },
    "scene": {
      "allOf": [
        {
          "type": "null"
        },
        {
          "$ref": "#/components/schemas/SceneResourceRelationshipToOne"
        }
      ]
    }
  }
}
```

Generated Rust SDK code:

```rust
pub struct GltfResourceSparseRelationshipsObject {
    #[serde(rename = "asset", skip_serializing_if = "Option::is_none")]
    pub asset: Option<Box<models::GltfResourceSparseRelationshipsObjectAsset>>,
    #[serde(rename = "scenes", skip_serializing_if = "Option::is_none")]
    pub scenes: Option<Box<models::GltfResourceSparseRelationshipsObjectScenes>>,
    #[serde(rename = "scene", skip_serializing_if = "Option::is_none")]
    pub scene: Option<Box<models::GltfResourceCreationRelationshipsScene>>,
}
```

In this case `GltfResourceSparseRelationshipsObject::scene`:

- Is typed as `Option<Option<Box<models::GltfResourceCreationRelationshipsScene>>>` when using the Utoipa 4 /OpenAPI 3.0 definition. :heavy_check_mark: 
- Is typed as `Option<Option<Box<models::GltfResourceCreationRelationshipsScene>>>` when using the Utoipa 5 /OpenAPI 3.1 definition.  :x:

**Comment by JMLX42** [comment] 2024-10-15 08:28
> is that the expected behavior? Is that the proper OpenAPI 3.1 to make nullable refs?

@juhaku The ChatGPT 4o says to use `oneOf` instead of `allOf`, which indeed makes more sense IMHO:

```yaml
components:
  schemas:
    ExampleSchema:
      type: object
      properties:
        exampleProperty:
          oneOf:
            - $ref: '#/components/schemas/SomeOtherSchema'
            - type: 'null'
```

**Comment by juhaku** [comment] 2024-10-15 08:31
@JMLX42 Sure, it should be quite easy, just to change few lines in `component.rs`.

**Comment by juhaku** [comment] 2024-10-15 08:33
> ChatGPT 4o says to use oneOf instead of allOf, which indeed makes more sense IMHO:

Yeah good point, `oneOf` makes more sense, it just there are no definite docs for how it actually should be presented, se I went by the `allOf`.

**Comment by JMLX42** [comment] 2024-10-15 10:31
@juhaku PR here: #1135

**Comment by juhaku** [comment] 2024-10-15 10:50
Great

**Comment by juhaku** [comment] 2024-10-15 11:22
I guess this can be closed as of now, but can be reopened if necessary.

**Closed by juhaku** 2024-10-15 11:22 UTC

**Comment by magnusja** [comment] 2024-10-29 21:17
Awesome that seems to work now thank you so much!
