### ISSUE TITLE
Question Compilation error: ToSchema called `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by AnatolyBuga** [juhaku/utoipa#543] opened 2023-03-25 19:13 UTC
I am getting an error on 

```rust
this function takes 1 argument but 0 arguments were supplied
    --> ultibi\ultibi_core\src\datarequest.rs:34:10
     |
34   | #[derive(ToSchema)]
     |          ^^^^^^^^ an argument is missing
     |
note: associated function defined here
    --> C:\Users\Anato\.cargo\registry\src\github.com-1ecc6299db9ec823\utoipa-3.1.2\src\openapi\schema.rs:1057:12
     |
1057 |     pub fn items<I: Into<RefOr<Schema>>>(mut self, component: I) -> Self {
     |            ^^^^^
     = note: this error originates in the derive macro `ToSchema` (in Nightly builds, run with -Z macro-backtrace for more info)
help: provide the argument
     |
34   | #[derive(ToSchema(/* value */))]
```

**As far as I can see ToShema derive doesn't take any arguments. Any thoughts?**

**Comment by AnatolyBuga** [comment] 2023-03-25 19:14
This is my code, although alot of type aliases - they are mostly strings and maps:
```rust
use utoipa::ToSchema;
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, Hash)]
#[serde(tag = "type")]
#[derive(ToSchema)]
pub struct AggregationRequest {
    // general fields
    #[serde(default)]
    pub name: Option<String>,
    /// Measure: (Name, Action) where Name will be looked up in
    /// MeasuresMap of the DataSet
    pub measures: Vec<(MeasureName, AggregationName)>,
    pub groupby: Vec<String>,
    #[serde(default)]
    pub filters: AndOrFltrChain,
    #[serde(default)]
    pub overrides: Vec<Override>,
    #[serde(default, alias = "additionalRows")]
    pub add_row: AdditionalRows,
    #[serde(default)]
    pub calc_params: CPM,
    /// drop rows where all results are NULL or 0
    #[serde(default)]
    pub hide_zeros: bool,
    /// Show totals
    #[serde(default)]
    pub totals: bool,
}
```

**Comment by juhaku** [comment] 2023-03-25 20:12
This is coming from the tuple syntax within your struct and is related to #330, #176 and is fixed in #541.
>```rust
>    /// Measure: (Name, Action) where Name will be looked up in
>    /// MeasuresMap of the DataSet
>    pub measures: Vec<(MeasureName, AggregationName)>,
> ```

Tuple support will be available after next release, but can be accessed now by pointing the cargo dependency to the master for time being.

**Comment by AnatolyBuga** [comment] 2023-03-26 12:48
@juhaku great, thank you very much.

**Comment by AnatolyBuga** [comment] 2023-03-26 20:33
@juhaku , sorry, another issue followed directly from that one. Happy to put it in a separate issue though if that helps.
`AggregationRequest` defined as above. 
```rust
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, Hash)]
#[serde(untagged)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
pub enum ComputeRequest {
    Aggregation(AggregationRequest),
    Breakdown,
}
```

This fails to compile with:
```
error: proc-macro derive panicked
  --> ultibi\ultibi_core\src\datarequest.rs:19:40
   |
19 | #[cfg_attr(feature = "openapi", derive(utoipa::ToSchema))]
   |                                        ^^^^^^^^^^^^^^^^
   |
   = help: message: called `Option::unwrap()` on a `None` value

error: could not compile `ultibi_core` due to previous error
```

**Comment by juhaku** [comment] 2023-03-26 20:41
Interesting, that still does not tell enough what is going on. How does the `AggregationRequest` look? what attribute is defined over it?

**Comment by AnatolyBuga** [comment] 2023-03-26 20:47
@juhaku thanks for quick reply. 

I will put together a proper reproducible example.

**Comment by AnatolyBuga** [comment] 2023-03-26 21:01
@juhaku , here we go:

```rust
use serde::Deserialize;
use serde::Serialize;

pub fn example() {
    ()
}


#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, Hash, utoipa::ToSchema)]
#[serde(tag = "type")]
pub struct AggregationRequest {
    #[serde(default)]
    pub name: Option<String>,
    pub measures: Vec<(String, String)>
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, Hash, utoipa::ToSchema)]
#[serde(untagged)]
pub enum ComputeRequest {
    Aggregation(AggregationRequest),
    Breakdown,
}
```

And:
```rust
serde = { version="*", features = ["derive", "rc"] }
serde_json = { version="*" }
utoipa = { git ="https://github.com/juhaku/utoipa", features = ["actix_extras"] }
```

**Comment by juhaku** [comment] 2023-03-26 21:44
Thanks for letting me know, this is a bug introduced here: https://github.com/juhaku/utoipa/pull/533

I'll fix this asap.

**Comment by juhaku** [comment] 2023-03-26 22:04
Moreover it is caused by the `#[serde(untagged)]` attribute. I need to check whether there is something that can be done to fix it or whether this scenario is actually not possible with OpenAPI.
> ```rust
> #[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, Hash, utoipa::ToSchema)]
> #[serde(untagged)] // <-- here
> pub enum ComputeRequest {
>     Aggregation(AggregationRequest),
>     Breakdown, /// <-- this causes the error, 
> }

**Comment by juhaku** [comment] 2023-03-26 23:12
@AnatolyBuga  And there you go, fix is on the way landing to master soon by #545.

**Closed** 2023-03-26 23:14 UTC

**Comment by AnatolyBuga** [comment] 2023-03-27 09:06
@juhaku thank you so much for promptly fixing this, and for the whole amazing library too.
