### ISSUE TITLE
ToSchema aliasing on rust types

### ISSUE THREAD

**Issue by michael-mark** [juhaku/utoipa#351] opened 2022-11-17 15:57 UTC
Hello all. I am trying out utoipa for the first time and was trying to create a Schema of a struct with a generic type. I was trying to follow the aliases way of handling this in the [documentation for the ToSchema macro](https://docs.rs/utoipa/latest/utoipa/derive.ToSchema.html#generic-schemas-with-aliases) but ran into some issues. In particular, the example provided does not seem to have the effect that I would expect.

This is a slightly modified version of the example provided in the documentation. 
```rust
use utoipa::{ToSchema, OpenApi};

#[derive(ToSchema)]
#[aliases(StatusMessage = Status<String>, StatusNumber = Status<i32>, StatusMore = Status<More>)]
struct Status<T> {
    value: T
}

/// An additional struct to demonstrate the differences between primitive types and defined structs
/// in the aliasing
#[derive(ToSchema)]
struct More {
    /// some inner information
    inner: String,
}

#[derive(OpenApi)]
#[openapi(
    components(schemas(StatusMessage, StatusNumber, StatusMore, More))
)]
struct ApiDoc;

fn main() {
    let doc = ApiDoc::openapi().to_pretty_json().expect("Unable to convert API docs to json");
    println!("{}", doc);
}
```

And this is the generated openapi doc from the code above (using utoipa version 2.3.0):
```json
{
  "openapi": "3.0.3",
  "info": {
    "title": "rust-playground",
    "description": "",
    "contact": {
      "name": ""
    },
    "license": {
      "name": ""
    },
    "version": "0.1.0"
  },
  "paths": {},
  "components": {
    "schemas": {
      "More": {
        "type": "object",
        "description": "An additional struct to demonstrate the differences between primitive types and defined structs",
        "required": [
          "inner"
        ],
        "properties": {
          "inner": {
            "type": "string",
            "description": "some inner information"
          }
        }
      },
      "StatusMessage": {
        "type": "object",
        "required": [
          "value"
        ],
        "properties": {
          "value": {
            "$ref": "#/components/schemas/String"
          }
        }
      },
      "StatusMore": {
        "type": "object",
        "required": [
          "value"
        ],
        "properties": {
          "value": {
            "$ref": "#/components/schemas/More"
          }
        }
      },
      "StatusNumber": {
        "type": "object",
        "required": [
          "value"
        ],
        "properties": {
          "value": {
            "$ref": "#/components/schemas/i32"
          }
        }
      }
    }
  }
}
```

The custom struct I added `More` is handled appropriately as it has it's own schema. However, the rust types `String` and `i32` don't seem to be handled properly. utoipa generates an openapi doc that suggests that `String` and `i32` are their own schemas that should have their own entry rather than being `"type": "string"`. 

Is this a bug with utoipa, or am I misinterpreting how to use the aliases properly?

**Comment by nkovacs** [comment] 2022-11-17 16:57
I ran into this same problem just now.

The way I solved it:

```
// First, add a trait to convert primitive types to the correct SchemaType

pub trait SchemaTyper {
    fn schema_type() -> utoipa::openapi::SchemaType;
}

impl SchemaTyper for String {
    fn schema_type() -> utoipa::openapi::SchemaType {
        utoipa::openapi::SchemaType::String
    }
}

impl SchemaTyper for i64 {
    fn schema_type() -> utoipa::openapi::SchemaType {
        utoipa::openapi::SchemaType::Integer
    }
}

impl SchemaTyper for f64 {
    fn schema_type() -> utoipa::openapi::SchemaType {
        utoipa::openapi::SchemaType::Number
    }
}

impl SchemaTyper for bool {
    fn schema_type() -> utoipa::openapi::SchemaType {
        utoipa::openapi::SchemaType::Boolean
    }
}

// add more impls

// then, create a helper that can be used in value_type

pub struct SchemaTypeHelper<T: SchemaTyper> {
    hack: std::marker::PhantomData<T>,
}


impl<T: SchemaTyper> ToSchema for SchemaTypeHelper<T> {
    fn schema() -> utoipa::openapi::schema::Schema {
        utoipa::openapi::ObjectBuilder::new()
            .schema_type(T::schema_type())
            .into()
    }
}

// modify the generic struct to use these:

#[derive(Serialize, ToSchema)]
#[serde(rename_all = "camelCase")]
pub struct Foo<T: SchemaTyper> {
    #[schema(inline, value_type = Option<SchemaTypeHelper<T>>)]
    pub default: Option<T>,
}

// and create the aliases manually:

pub type FormFieldString = FormField<String>;
pub type FormFieldInt = FormField<i64>;
pub type FormFieldFloat = FormField<f64>;
pub type FormFieldBool = FormField<bool>;
```

Since `Toschema` isn't implemented for primitive types, I had to use a generic helper and value_type.

**Comment by michael-mark** [comment] 2022-11-17 17:40
@nkovacs, Thank you for this workaround. I modified your solution slightly to work for my use case as my generics are over types that also implement ToSchema on their own. My solution looks something like this: 

```rust
use utoipa::{ToSchema, OpenApi};

/// An additional struct to demonstrate the differences between primitive types and defined structs
/// in the aliasing
#[derive(ToSchema)]
struct More {
    /// some inner information
    inner: String,
}

pub trait CustomSchema {
    /// Returns the schema for the type implementing this 
    fn schema() -> utoipa::openapi::Schema;
}

struct CustomSchemaHelper<T: CustomSchema> {
    hack: std::marker::PhantomData<T>,
}

impl<T: CustomSchema> ToSchema for CustomSchemaHelper<T> {
    fn schema() -> utoipa::openapi::schema::Schema {
        <T as CustomSchema>::schema()
    }
}

impl CustomSchema for String {
    fn schema() -> utoipa::openapi::Schema {
        utoipa::openapi::ObjectBuilder::new()
            .schema_type(utoipa::openapi::SchemaType::String)
            .into()
    }
}

impl CustomSchema for i32 {
    fn schema() -> utoipa::openapi::Schema {
        utoipa::openapi::ObjectBuilder::new()
            .schema_type(utoipa::openapi::SchemaType::Number)
            .into()
    }
}

impl CustomSchema for More {
    fn schema() -> utoipa::openapi::Schema {
        <More as utoipa::ToSchema>::schema()
    }
}

type StatusMessage = Status<String>;
type StatusNumber = Status<i32>;
type StatusMore = Status<More>;

#[derive(ToSchema)]
struct Status<T: CustomSchema> {
    #[schema(inline, value_type = CustomSchemaHelper<T>)]
    value: T
}

#[derive(OpenApi)]
#[openapi(
    components(schemas(StatusMessage, StatusNumber, StatusMore, More))
)]
struct ApiDoc;

fn main() {
    let doc = ApiDoc::openapi().to_pretty_json().expect("Unable to convert API docs to json");
    println!("{}", doc);
}
```
Produces
```json
{
  "openapi": "3.0.3",
  "info": {
    "title": "rust-playground",
    "description": "",
    "contact": {
      "name": ""
    },
    "license": {
      "name": ""
    },
    "version": "0.1.0"
  },
  "paths": {},
  "components": {
    "schemas": {
      "More": {
        "type": "object",
        "description": "An additional struct to demonstrate the differences between primitive types and defined structs",
        "required": [
          "inner"
        ],
        "properties": {
          "inner": {
            "type": "string",
            "description": "some inner information"
          }
        }
      },
      "StatusMessage": {
        "type": "object",
        "required": [
          "value"
        ],
        "properties": {
          "value": {
            "type": "string"
          }
        }
      },
      "StatusMore": {
        "type": "object",
        "required": [
          "value"
        ],
        "properties": {
          "value": {
            "type": "object",
            "description": "An additional struct to demonstrate the differences between primitive types and defined structs",
            "required": [
              "inner"
            ],
            "properties": {
              "inner": {
                "type": "string",
                "description": "some inner information"
              }
            }
          }
        }
      },
      "StatusNumber": {
        "type": "object",
        "required": [
          "value"
        ],
        "properties": {
          "value": {
            "type": "number"
          }
        }
      }
    }
  }
}
```

**Comment by nkovacs** [comment] 2022-11-17 17:57
Yeah, unfortunately for that you'd have to implement ToSchema manually for Status. The problem is that the derive generates `<CustomSchemaHelper<T> as utoipa::ToSchema>::schema()` for the value field if you use inline (and you have to use inline, otherwise it will reference a "CustomSchemaHelper" schema, which won't work), and you can't return `Ref` from `CustomSchemaHelper`'s `schema()` either. We'd need a different attribute that accepts a function that returns `RefOr<Schema>`.

**Comment by juhaku** [comment] 2022-11-29 21:45
I need to investigate this when I get time to and I'll report here when I know more. If there is some fix that can be done I am happy to include it to the crate. :slightly_smiling_face:

**Comment by juhaku** [comment] 2022-12-06 22:28
@fdoyon @nkovacs @michael-mark Fix is on they way and soon to be merged.

**Closed** 2022-12-06 22:38 UTC
Labels: bug
