### ISSUE TITLE
request can not finished for big response

### ISSUE THREAD

**Issue by Exclamation-mark** [juhaku/utoipa#711] opened 2023-07-28 02:55 UTC
But `curl` can fetch data.

<img width="1055" alt="image" src="https://github.com/vikadata/vikadata/assets/18455767/c5daf968-78b5-4199-8550-ef868dc05516">

<img width="581" alt="image" src="https://github.com/juhaku/utoipa/assets/18455767/08e6c9a9-3e38-4099-ae5b-d2a4113ac8f7">

**Comment by juhaku** [comment] 2023-07-28 06:30
If I read this right that you are talking about Swagger UI cannot handle big payloads then the issue is not in utoipa but in the Swagger UI itself. Moreover the utoipa is only a metadata generative library and has nothing to do with networking. 

Perhaps looking for solutions from Swagger UI related forums first and then if there is a fix in some version of Swagger UI which is newer than the one utoipa has, then come  back with PR that updates the Swagger UI or with the request to do so.

**Comment by juhaku** [comment] 2023-08-07 23:27
Closing as non actionable.

**Closed by juhaku** 2023-08-07 23:27 UTC
