### ISSUE TITLE
Serde renamed params are ignored by `IntoParams` in `actix_web`

### ISSUE THREAD

**Issue by JSH32** [juhaku/utoipa#270] opened 2022-09-03 01:01 UTC
Just as the title says. Something like this does not get renamed in the generated JSON. There is no way to manually rename this either.
```rs
#[derive(Deserialize, IntoParams)]
#[serde(rename_all = "camelCase")]
pub struct RegistrationKeyParams {
    /// Maximum amount of key uses.
    pub max_uses: Option<i32>,
}
```

**Comment by juhaku** [comment] 2022-09-03 10:01
Yes, at the moment renaming capability is unimplemented for `IntoParams` types. Like the docs says partial serde attribute support is currently only supported in `ToSchema` types. 

This is something that need to be done for further releases.

**Comment by JSH32** [comment] 2022-09-03 21:25
Might I suggest using [serde_aux](https://crates.io/crates/serde-aux) for this? I assume the reason that it's not supported is because it handles the parsing differently than schema, which relies on being a json form and thus using `serde_json`. `serde_aux` has introspection features that can get the post-processed name of fields in a struct in order. You could also just have a per-field `rename` attribute if that is proffered. As long as there is some way to rename fields.

**Comment by juhaku** [comment] 2022-09-04 11:51
Yeah, that is the case, the schema and the serde deserialized types are totally disconnected from each other, like serde deserializes json when request is processed at server. But when schema is generated it does not deserialize or serialize any json.  This is same for `ToSchema` as well however there is already implementation for renaming fields in place which is pretty much same as in `serde` crate has but it has not been used in `IntoParams` yet. 

Interesting idea, and at first I was tempted to see whether using this would bring any overhead to the library. However I'm afraid that it will not work, becuase the `serde-aux` introspect needs a type which will be introspected which in turn will execute serde derive macros to deserialize the type and collect the names only. The problem is that the `utoipa` itself is a macro which is executed when macro compiles and it does not have concrete types but instead of a token stream of types represented at compile time. Thus I could generate the code which in turn would call the introspection but there is no way to execute it at compilation time and expect result which then would be used in compilation time to generate rest of the schema.

**Comment by juhaku** [comment] 2022-11-21 20:02
Fixed with #339 and #354

**Closed by juhaku** 2022-11-21 20:02 UTC
