### ISSUE TITLE
`#[derive(ToSchema)]` fails on `time::Date` fields

### ISSUE THREAD

**Issue by Kinrany** [juhaku/utoipa#398] opened 2022-12-08 15:15 UTC
Repro:

```rust
use time; // 0.3.17
use utoipa; // 2.4.2, features = ["time"]

#[derive(utoipa::ToSchema)]
struct Foo {
    bar: time::Date,
}
```

Expanded:

```rust
struct Foo {
    bar: time::Date,
}
impl utoipa::ToSchema for Foo {
    fn schema() -> utoipa::openapi::schema::Schema {
        utoipa::openapi::ObjectBuilder::new()
            .property(
                "bar",
                utoipa::openapi::ObjectBuilder::new()
                    .schema_type(utoipa::openapi::SchemaType::String)
                    .format(Some()),                                          // <- note the "Some()"
            )
            .required("bar")
            .into()
    }
}
```

Error:

```
error[E0061]: this enum variant takes 1 argument but 0 arguments were supplied
   --> src/lib.rs:12:29
    |
12  |                     .format(Some()),
    |                             ^^^^-- an argument of type `SchemaFormat` is missing
    |
note: tuple variant defined here
   --> /Users/kinrany/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/option.rs:526:5
    |
526 |     Some(#[stable(feature = "rust1", since = "1.0.0")] T),
    |     ^^^^
help: provide the argument
    |
12  |                     .format(Some(/* SchemaFormat */)),
    |                                 ~~~~~~~~~~~~~~~~~~~~

For more information about this error, try `rustc --explain E0061`.
error: could not compile `repro-utoipa-time-toschema-derive` due to previous error
```

~~As far as I understand, the correct macro output in this case would be `Some(SchemaFormat::KnownFormat(KnownFormat::Date))`.~~

**Comment by Kinrany** [comment] 2022-12-08 15:32
This doesn't happen with `chrono::NaiveDate`. Expansion:

```rust
struct Foo {
    bar: chrono::NaiveDate,
}
impl utoipa::ToSchema for Foo {
    fn schema() -> utoipa::openapi::schema::Schema {
        utoipa::openapi::ObjectBuilder::new()
            .property(
                "bar",
                utoipa::openapi::Ref::from_schema_name("chrono.NaiveDate"),
            )
            .required("bar")
            .into()
    }
}
```

**Comment by juhaku** [comment] 2022-12-08 19:25
Oops. This is a bug caused by a typo in `utoipa-gen` crate. Will push a fix to latest master. However I cannot make a release just yet, because there are already some breaking changes that will be introduced along with the next release. And there is still some things to be done to the release. 

However you can either use the master directly preferably with specific commit point. Or you can alternatively for time being define format manually for the type.
```rust
struct Bar {
  #[schema(format = Date)]
  foo: Date
}
```

**Comment by Kinrany** [comment] 2022-12-08 19:37
Thank you!

`#[schema(format = Date)]` doesn't seem to help on its own, but `#[schema(value_type = String, format = Date)]` or just `#[schema(value_type = String)]` does.

**Comment by juhaku** [comment] 2022-12-08 19:46
Good.

**Closed** 2022-12-08 19:58 UTC
Labels: bug
